{% set version = "2.0.0" %}

package:
  name: mi-programoptions
  version: {{ version }}

source:
  url: https://github.com/metno/mi-programoptions/archive/v{{ version }}.tar.gz
  sha256: a325f680d7a7e13d0061b6ab96ce09d188eea0073bd17d79605a31d171315832
  folder: source

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make         # [not win]
    - ninja        # [win]
  host:
    - mi-cpptest

test:
  commands:
    - test -f $PREFIX/include/mi_programoptions.h  # [unix]
    - test -f $PREFIX/lib/libmi-programoptions$SHLIB_EXT  # [unix]

about:
  home: https://github.com/metno/mi-programoptions
  license: GPL-2.0-or-later
  license_file: source/LICENSE.txt
  summary: 'MET Norway program options library'

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
